num1 = int(input("Enter 1st number:: "))
num2 = int(input("Enter 2nd number:: "))
num3 = int(input("Enter 3rd number:: "))
largest_num = max(num1, num2, num3)
print(f"The largest number is: {largest_num}")